# Generated by Django 5.2 on 2025-05-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('summary', models.TextField()),
                ('recommendation', models.CharField(max_length=50)),
                ('predicted_price', models.FloatField()),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
