# Generated by Django 5.2 on 2025-05-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentanalysis',
            name='recommendation',
            field=models.CharField(max_length=1000),
        ),
    ]
