# Generated by Django 5.2 on 2025-05-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0002_alter_sentimentanalysis_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentanalysis',
            name='recommendation',
            field=models.CharField(max_length=2000),
        ),
    ]
